const cars=D.map((d,i)=>{let[b,m,t,p,r,k,g,tr]=d,be=t.includes('BEV'),ph=t.includes('PHEV')||t.includes('EREV'),mh=t.includes('MHEV'),z=be?(p<3e5?.38:.42):ph?(p<3e5?.4:.44):mh?.43:.45,ins=Math.round(Math.max(be?3500:ph?4200:mh?3800:4000,p*(be?.035:ph?.032:mh?.031:.03))),man=Math.round(p*(be?.05:ph?.105:mh?.085:.09)),sh=be?1:ph?(r&&r<90?.7:.8):0,c={brand:b,model:m,type:t,cpf:p,cnpj:p,pcd:p,insurance:ins,maintenance:man,residual:z,kwh100:k,gasKml:g,ethKml:g&&t.includes('Flex')?Math.round(g*.72*10)/10:null,electricShare:sh,ethShare:0,evRange:r,totalRange:tr,status:'Estimativa comparativa'};if(S[i]){[c.cnpj,c.pcd,c.insurance,c.maintenance,c.residual]=S[i];c.status='Pesquisa específica'}return c});

const $=id=>document.getElementById(id),fmt=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(v),nf=v=>new Intl.NumberFormat('pt-BR',{maximumFractionDigits:2}).format(v),sel=$('selectors'),mode=$('mode'),weekly=$('weekly'),years=$('years'),energy=$('energy'),gas=$('gas'),ethanol=$('ethanol'),uf=$('uf'),utility=$('utility'),tariffFlag=$('tariffFlag'),ipvaRate=$('ipvaRate'),localPurchase=$('localPurchase'),summary=$('summary'),tableWrap=$('tableWrap'),maintenanceNotes=$('maintenanceNotes'),regionalMeta=$('regionalMeta'),brands=[...new Set(cars.map(c=>c.brand))].sort((a,b)=>a.localeCompare(b,'pt-BR'));

function priceForMode(c){return c[mode.value==='PcD'?'pcd':mode.value.toLowerCase()]}
function opts(i){let h=`<option value=''>${i<2?'Selecione um modelo':'Selecione um modelo (opcional)'}</option>`;for(const b of brands){h+=`<optgroup label='${b}'>`;cars.forEach((c,j)=>{if(c.brand===b)h+=`<option value='${j}'>${c.model} — ${c.type} — ${fmt(priceForMode(c))}</option>`});h+='</optgroup>'}return h}
function refreshSelectors(initial=false){const ss=[...sel.querySelectorAll('select')],prev=ss.map(s=>s.value);ss.forEach((s,i)=>{const keep=prev[i];s.innerHTML=opts(i);if(keep!==undefined&&keep!=='')s.value=keep});if(initial){const d=cars.findIndex(c=>c.brand==='BYD'&&c.model==='Dolphin GS'),o=cars.findIndex(c=>c.brand==='GWM'&&c.model==='ORA 5');if(ss[0])ss[0].value=d>=0?d:0;if(ss[1])ss[1].value=o>=0?o:1}}

function isBev(c){return c.type.includes('BEV')||c.type==='Elétrico'}
function isHybrid(c){return !isBev(c)&&(/HEV|PHEV|MHEV|EREV|Híbrido/i).test(c.type)}
function regionalIpva(c,state,calendarYear,ownershipYear,baseRate,boughtLocally){
  const bev=isBev(c),hybrid=isHybrid(c),electrified=bev||hybrid,standard={rate:baseRate,label:'Alíquota padrão da UF',conditional:false};
  if(state==='AL'&&electrified){const rate=ownershipYear===0?0:ownershipYear===1?(bev?.005:.0075):(bev?.01:.015);return{rate,label:ownershipYear===0?'Isenção no 1º ano':`Alíquota reduzida de ${nf(rate*100)}%`,conditional:false}}
  if(state==='AM'&&electrified)return{rate:.015,label:'Alíquota estadual de 1,5%',conditional:false};
  if(state==='BA'&&bev&&c.cpf<=300000)return{rate:0,label:'Isenção para elétrico até R$ 300 mil (requer solicitação)',conditional:false};
  if(state==='CE'&&bev)return{rate:baseRate*.5,label:'Redução de 50% para elétrico',conditional:false};
  if(state==='DF'&&electrified&&boughtLocally)return{rate:0,label:'Isenção para elétrico/híbrido — compra local informada',conditional:false};
  if(state==='DF'&&electrified)return{...standard,label:'Benefício condicionado à documentação e aquisição elegível',conditional:true};
  if(state==='MG'&&electrified)return{...standard,label:'Possível isenção no ano da compra se fabricado em MG e dentro do limite legal',conditional:true};
  if(state==='PB'&&bev)return{rate:0,label:'Isenção para veículo 100% elétrico',conditional:false};
  if(state==='PE'&&bev)return{rate:0,label:'Isenção para veículo 100% elétrico',conditional:false};
  if(state==='RJ'&&bev)return{rate:.005,label:'Alíquota reduzida de 0,5%',conditional:false};
  if(state==='RJ'&&hybrid)return{rate:.015,label:'Alíquota reduzida de 1,5%',conditional:false};
  if(state==='RN'&&bev)return{rate:0,label:'Isenção para veículo com motor elétrico',conditional:false};
  if(state==='SP'&&hybrid&&c.type.includes('Flex')&&c.cpf<=261154.45)return{...standard,label:'Benefício potencial: exige potência, tensão da bateria e demais requisitos legais',conditional:true};
  if(state==='TO'&&electrified&&boughtLocally){let factor=calendarYear<=2027?0:calendarYear===2028?.5:calendarYear===2029?.6:calendarYear===2030?.7:1;return{rate:baseRate*factor,label:factor===0?'Isenção 2026–2027 para compra em concessionária do TO':`Redução de ${nf((1-factor)*100)}% na base — compra local`,conditional:false}}
  if(state==='TO'&&electrified)return{...standard,label:'Benefício condicionado à compra em concessionária do Tocantins',conditional:true};
  return standard;
}

function calc(c,m,w,y,e,g,et,state,insFactor,baseRate,boughtLocally){
  const kmAnnual=w*52,km=kmAnnual*y,p=c[m==='PcD'?'pcd':m.toLowerCase()],market=c.cpf,res=market*c.residual,dep=Math.max(0,p-res),insuranceAnnual=c.insurance*insFactor,ins=insuranceAnnual*y,maintenanceAnnual=c.maintenance*(kmAnnual/156000),man=maintenanceAnnual*y,ipvaAnnual=m==='PcD'?0:market*baseRate;let ipva=0,ipvaStandard=0,labels=[],conditional=false;
  for(let a=0;a<y;a++){const venal=market*(1-(1-c.residual)*(a/(y-1||1)));if(m!=='PcD'){const rule=regionalIpva(c,state,2026+a,a,baseRate,boughtLocally);ipva+=venal*rule.rate;ipvaStandard+=venal*baseRate;labels.push(rule.label);conditional=conditional||rule.conditional}else labels.push('Isenção PcD preservada do Modelo 0')}
  const electricKm=km*c.electricShare,fuelKm=km-electricKm,elec=c.kwh100?electricKm*c.kwh100/100*e*1.1:0,fuel=fuelKm&&c.gasKml?fuelKm*((1-c.ethShare)*g/c.gasKml+(c.ethShare&&c.ethKml?c.ethShare*et/c.ethKml:0)):0,tco=dep+ins+man+ipva+elec+fuel;
  return{price:p,residual:res,depreciation:dep,insuranceAnnual,insurance:ins,maintenanceAnnual,maintenance:man,ipvaAnnual,ipva,ipvaStandard,ipvaSaving:Math.max(0,ipvaStandard-ipva),ipvaLabel:[...new Set(labels)].join(' • '),ipvaConditional:conditional,energyAnnual:elec/y,elec,fuelAnnual:fuel/y,fuel,tco,tcoAnnual:tco/y,monthly:tco/(y*12),perkm:km?tco/km:0}
}

function selectedDistributor(){return REGIONAL_DB.distributors[uf.value][Number(utility.value)||0]}
function maintenanceLegend(data){
  const items=data.map(({c})=>{
    const plan=MAINTENANCE_DB.forCar(c),name=`${c.brand} ${c.model}`,sourceLink=plan.url&&plan.url!=='#'?` <a href='${plan.url}' target='_blank' rel='noopener'>fonte da montadora</a>`:'';
    if(plan.kind==='condition')return `<li><strong>${name}:</strong> a montadora não adota intervalo fixo; a revisão é indicada pelo ${plan.system}. ${plan.note}${sourceLink}</li>`;
    return `<li><strong>${name}:</strong> a montadora sugere manutenção a cada <strong>${new Intl.NumberFormat('pt-BR').format(plan.km)} km</strong> ou a cada <strong>${plan.months} meses</strong>, o que ocorrer primeiro.${plan.note?` ${plan.note}`:''}${sourceLink}</li>`;
  }).join('');
  maintenanceNotes.innerHTML=`<div class='maintenanceNoteTitle'><sup>1</sup><strong>Intervalos recomendados pelas montadoras</strong></div><ul>${items}</ul><p class='maintenanceDisclaimer'>Os intervalos consideram uso normal. Uso severo, versão e ano-modelo podem antecipar serviços; confirme sempre o manual do veículo.</p>`;
}
function updateEnergy(){const distributor=selectedDistributor(),flag=REGIONAL_DB.energyFlags[tariffFlag.value];energy.value=(distributor[1]+flag.surcharge).toFixed(5);showRegionalMeta();render()}
function showRegionalMeta(){const state=uf.value,dist=selectedDistributor(),flag=REGIONAL_DB.energyFlags[tariffFlag.value],fuel=REGIONAL_DB.fuel[state],distNote=dist&&dist[2]?`<span class='alert'>⚠ ${dist[2]}</span>`:'',taxNote=REGIONAL_DB.ipva[state].note?`<span class='alert'>IPVA: ${REGIONAL_DB.ipva[state].note}; ajuste o campo se necessário.</span>`:'';regionalMeta.innerHTML=`<span><strong>${REGIONAL_DB.states[state]}</strong>: energia-base R$ ${nf(dist[1])}/kWh + bandeira R$ ${nf(flag.surcharge)}/kWh</span><span>Gasolina R$ ${nf(fuel.gas)}/L • Etanol ${fuel.eth==null?'sem amostra estadual; valor manual mantido':'R$ '+nf(fuel.eth)+'/L'}</span><span>Seguro regional aplicado automaticamente • IPVA padrão ${nf(+ipvaRate.value)}%</span>${distNote}${taxNote}<span>Fontes: <a href='${REGIONAL_DB.sources.fuel.url}' target='_blank' rel='noopener'>ANP</a>, <a href='${REGIONAL_DB.sources.energy.url}' target='_blank' rel='noopener'>ANEEL</a> e <a href='${REGIONAL_DB.sources.insurance.url}' target='_blank' rel='noopener'>SUSEP</a>.</span>`}
function updateState(){const state=uf.value,fuel=REGIONAL_DB.fuel[state],distributors=REGIONAL_DB.distributors[state];utility.innerHTML=distributors.map((d,i)=>`<option value='${i}'>${d[0]}</option>`).join('');gas.value=fuel.gas.toFixed(2);if(fuel.eth!=null)ethanol.value=fuel.eth.toFixed(2);ipvaRate.value=(REGIONAL_DB.ipva[state].rate*100).toFixed(2);updateEnergy()}

function render(){
  const m=mode.value,w=+weekly.value,y=+years.value,e=+energy.value,g=+gas.value,et=+ethanol.value,state=uf.value,insFactor=REGIONAL_DB.insuranceFactor[state],baseRate=+ipvaRate.value/100,boughtLocally=localPurchase.value==='yes';let ids=[...sel.querySelectorAll('select')].map(s=>s.value).filter(v=>v!=='').map(Number);ids=[...new Set(ids)].slice(0,6);if(!ids.length){summary.innerHTML='';tableWrap.innerHTML='';maintenanceNotes.innerHTML='';return}
  const data=ids.map(i=>({c:cars[i],r:calc(cars[i],m,w,y,e,g,et,state,insFactor,baseRate,boughtLocally)})),best=Math.min(...data.map(x=>x.r.tco)),winner=data.find(x=>x.r.tco===best),dist=selectedDistributor(),ipvaSource=REGIONAL_DB.incentives[state];
  summary.innerHTML=`<div class='kpi'><small>Melhor TCO</small><strong>${winner.c.brand} ${winner.c.model}</strong></div><div class='kpi'><small>TCO em ${y} anos</small><strong>${fmt(best)}</strong></div><div class='kpi'><small>Custo mensal</small><strong>${fmt(winner.r.monthly)}</strong></div><div class='kpi'><small>Maior economia de IPVA</small><strong>${fmt(Math.max(...data.map(x=>x.r.ipvaSaving)))}</strong></div>`;
  const horizon=y===1?'1 Ano':`${y} Anos`,tcoPeriodLabel=`TCO em ${horizon}`;
  const rule=x=>`<span class='ruleTag${x.r.ipvaConditional?' conditional':''}'>${x.r.ipvaLabel}</span>${ipvaSource?` <a class='mutedValue' href='${ipvaSource.url}' target='_blank' rel='noopener'>fonte oficial</a>`:''}`,metrics=[['UF da residência',()=>`${REGIONAL_DB.states[state]} (${state})`],['Distribuidora',()=>dist[0]],['Motorização',x=>`<span class='tag'>${x.c.type}</span>`],['Preço de compra',x=>fmt(x.r.price)],['Preço varejo/CPF',x=>fmt(x.c.cpf)],['Preço CNPJ',x=>fmt(x.c.cnpj)],['Preço PcD',x=>fmt(x.c.pcd)],['Autonomia elétrica',x=>x.c.evRange?x.c.evRange+' km':'—'],['Autonomia total/ref.',x=>x.c.totalRange?x.c.totalRange+' km':'—'],['Consumo elétrico',x=>x.c.kwh100?x.c.kwh100+' kWh/100 km':'—'],['Consumo gasolina',x=>x.c.gasKml?x.c.gasKml+' km/l':'—'],['Consumo etanol',x=>x.c.ethKml?x.c.ethKml+' km/l':'—'],['% km elétrico usado no TCO',x=>Math.round(x.c.electricShare*100)+'%'],['Seguro anual',x=>fmt(x.r.insuranceAnnual)],[`Seguro em ${horizon}`,x=>fmt(x.r.insurance)],['Revisão/Manutenção Anual<sup>1</sup>',x=>fmt(x.r.maintenanceAnnual)],[`Revisão/manutenção em ${horizon}<sup>1</sup>`,x=>fmt(x.r.maintenance)],['IPVA anual',x=>fmt(x.r.ipvaAnnual)],[`IPVA sem incentivo em ${horizon}`,x=>fmt(x.r.ipvaStandard)],['Economia de IPVA',x=>`<span class='saving'>${fmt(x.r.ipvaSaving)}</span>`],['IPVA aplicado',x=>fmt(x.r.ipva)],['Regra do IPVA',rule],['Energia anual',x=>fmt(x.r.energyAnnual)],[`Energia em ${horizon}`,x=>fmt(x.r.elec)],['Combustível anual',x=>fmt(x.r.fuelAnnual)],[`Combustível em ${horizon}`,x=>fmt(x.r.fuel)],[`Depreciação em ${horizon}`,x=>fmt(x.r.depreciation)],['Valor residual estimado',x=>fmt(x.r.residual)],['TCO mensal',x=>fmt(x.r.monthly)],['TCO Anual',x=>fmt(x.r.tcoAnnual)],[tcoPeriodLabel,x=>fmt(x.r.tco)],['TCO por km',x=>'R$ '+nf(x.r.perkm)]];
  let html='<table><thead><tr><th>Parâmetro</th>'+data.map(x=>'<th>'+x.c.brand+' '+x.c.model+'</th>').join('')+'</tr></thead><tbody>';for(const[label,value]of metrics)html+='<tr><td>'+label+'</td>'+data.map(x=>`<td class='${label===tcoPeriodLabel&&x.r.tco===best?'best':''}'>${value(x)}</td>`).join('')+'</tr>';tableWrap.innerHTML=html+'</tbody></table>';maintenanceLegend(data)
}

uf.innerHTML=Object.entries(REGIONAL_DB.states).map(([code,name])=>`<option value='${code}'>${name} (${code})</option>`).join('');uf.value='MG';tariffFlag.innerHTML=Object.entries(REGIONAL_DB.energyFlags).map(([code,item])=>`<option value='${code}'>${item.label}</option>`).join('');tariffFlag.value=REGIONAL_DB.currentFlag;refreshSelectors(true);$('catalogCount').textContent=cars.length;updateState();
$('compare').onclick=render;[weekly,years,energy,gas,ethanol,ipvaRate,localPurchase].forEach(input=>input.addEventListener('change',()=>{showRegionalMeta();render()}));mode.addEventListener('change',()=>{refreshSelectors();render()});uf.addEventListener('change',updateState);utility.addEventListener('change',updateEnergy);tariffFlag.addEventListener('change',updateEnergy);sel.addEventListener('change',render);render();
